"""Constantes de los linters de prosa: listas cerradas y umbrales (018-I5, `definitions.md` §11.2).

Nadie las ajusta, así que viven en `domain` y no en `config`.
"""

from __future__ import annotations

#: Artículos, preposiciones, conjunciones, pronombres y formas de ser, estar y haber.
#: No cuentan para `linter-repeticion` (018-C1).
GRAMMATICAL_WORDS: frozenset[str] = frozenset(
    {
        # Artículos
        "el",
        "la",
        "los",
        "las",
        "un",
        "una",
        "unos",
        "unas",
        "lo",
        # Preposiciones
        "a",
        "ante",
        "bajo",
        "cabe",
        "con",
        "contra",
        "de",
        "desde",
        "durante",
        "en",
        "entre",
        "hacia",
        "hasta",
        "mediante",
        "para",
        "por",
        "segun",
        "según",
        "sin",
        "so",
        "sobre",
        "tras",
        # Conjunciones
        "y",
        "e",
        "ni",
        "o",
        "u",
        "pero",
        "mas",
        "sino",
        "que",
        "si",
        "porque",
        "aunque",
        "pues",
        "como",
        "cuando",
        "mientras",
        # Pronombres
        "yo",
        "tu",
        "tú",
        "ella",
        "usted",
        "nosotros",
        "nosotras",
        "vosotros",
        "vosotras",
        "ellos",
        "ellas",
        "ustedes",
        "me",
        "te",
        "se",
        "nos",
        "os",
        "le",
        "les",
        "mi",
        "mí",
        "mis",
        "su",
        "sus",
        "tus",
        "ti",
        "sí",
        "conmigo",
        "contigo",
        "consigo",
        "nuestro",
        "nuestra",
        "nuestros",
        "nuestras",
        "vuestro",
        "vuestra",
        "vuestros",
        "vuestras",
        "este",
        "esta",
        "esto",
        "estos",
        "estas",
        "ese",
        "esa",
        "eso",
        "esos",
        "esas",
        "aquel",
        "aquella",
        "aquello",
        "aquellos",
        "aquellas",
        "quien",
        "quienes",
        "cual",
        "cuales",
        "cuyo",
        "cuya",
        "cuyos",
        "cuyas",
        # Formas de ser
        "soy",
        "eres",
        "es",
        "somos",
        "sois",
        "son",
        "era",
        "eras",
        "eramos",
        "éramos",
        "erais",
        "eran",
        "fui",
        "fuiste",
        "fue",
        "fuimos",
        "fuisteis",
        "fueron",
        "sere",
        "seré",
        "seras",
        "serás",
        "sera",
        "será",
        "seremos",
        "sereis",
        "seréis",
        "seran",
        "serán",
        "sea",
        "seas",
        "seamos",
        "seais",
        "seáis",
        "sean",
        "seria",
        "sería",
        "serias",
        "serías",
        "seriamos",
        "seríamos",
        "seriais",
        "seríais",
        "serian",
        "serían",
        "siendo",
        "sido",
        # Formas de estar
        "estoy",
        "estás",
        "está",
        "estamos",
        "estais",
        "estáis",
        "estan",
        "están",
        "estaba",
        "estabas",
        "estabamos",
        "estábamos",
        "estabais",
        "estaban",
        "estuve",
        "estuviste",
        "estuvo",
        "estuvimos",
        "estuvisteis",
        "estuvieron",
        "estes",
        "estés",
        "estemos",
        "esteis",
        "estéis",
        "esten",
        "estén",
        "estando",
        "estado",
        # Formas de haber
        "he",
        "has",
        "ha",
        "hemos",
        "habeis",
        "habéis",
        "han",
        "habia",
        "había",
        "habias",
        "habías",
        "habiamos",
        "habíamos",
        "habiais",
        "habíais",
        "habian",
        "habían",
        "hube",
        "hubiste",
        "hubo",
        "hubimos",
        "hubisteis",
        "hubieron",
        "habre",
        "habré",
        "habras",
        "habrás",
        "habra",
        "habrá",
        "habremos",
        "habreis",
        "habréis",
        "habran",
        "habrán",
        "haya",
        "hayas",
        "hayamos",
        "hayais",
        "hayáis",
        "hayan",
        "habiendo",
        "habido",
        "hay",
    }
)

#: Una palabra repetida dispara `linter-repeticion` a partir de esta cuenta en un párrafo.
WORD_REPETITION_THRESHOLD = 3

#: Muletillas: frases hechas que empobrecen la prosa si se repiten (018-C2).
FILLER_PHRASES: tuple[str, ...] = (
    "de repente",
    "entonces",
    "en ese momento",
    "de alguna manera",
)

#: Una muletilla repetida dispara `linter-repeticion` a partir de esta cuenta en un párrafo.
FILLER_REPETITION_THRESHOLD = 2

#: Densidad de adverbios en -mente por 1.000 palabras que dispara `linter-estilo-ia` (018-C9).
MENTE_DENSITY_THRESHOLD = 6.0

#: Palabras en -mente que no son adverbios: sustantivos, adjetivos y formas de verbos en
#: -mentar (018-C10). Lista cerrada del dominio.
MENTE_EXCEPTIONS: frozenset[str] = frozenset(
    {
        "mente",
        "demente",
        "clemente",
        "vehemente",
        "comente",
        "aumente",
        "lamente",
    }
)

#: Clichés y giros típicos de texto generado (018-C11). Lista cerrada del dominio.
CLICHES: tuple[str, ...] = (
    "un escalofrío le recorrió la espalda",
    "el tiempo pareció detenerse",
    "sin lugar a dudas",
)

#: Marcas de primera persona, para `linter-consistencia` (018-C12, 018-C13).
FIRST_PERSON_MARKS: frozenset[str] = frozenset(
    {
        "yo",
        "me",
        "mí",
        "mi",
        "mis",
        "conmigo",
        "nosotros",
        "nosotras",
        "nos",
        "nuestro",
        "nuestra",
        "nuestros",
        "nuestras",
    }
)

#: Marcas del tratamiento de tú, para `linter-consistencia` (018-C14, 018-C15).
TU_TREATMENT_MARKS: frozenset[str] = frozenset({"tú", "tu", "tus", "te", "ti", "contigo"})

#: Marcas del tratamiento de usted, para `linter-consistencia` (018-C14, 018-C15).
USTED_TREATMENT_MARKS: frozenset[str] = frozenset({"usted"})

#: Nombre de cada tratamiento, para el mensaje de aviso (018-C14, 018-C15).
TREATMENT_DISPLAY_NAMES: dict[str, str] = {"tu": "tú", "usted": "usted"}
