/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/novels/{novel_id}/story-bible": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Story Bible */
        get: operations["get_story_bible_api_novels__novel_id__story_bible_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/novels/{novel_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Versions */
        get: operations["list_versions_api_novels__novel_id__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/novels/{novel_id}/versions/{number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Version */
        get: operations["get_version_api_novels__novel_id__versions__number__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/novels/{novel_id}/versions/{number}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Version Pdf */
        get: operations["get_version_pdf_api_novels__novel_id__versions__number__pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/view/versions/{version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** View Version */
        get: operations["view_version_view_versions__version_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BirthEntry */
        BirthEntry: {
            /** Character Id */
            character_id: number;
            /**
             * Birth Date
             * Format: date
             */
            birth_date: string;
        };
        /**
         * CapituloVista
         * @description Un capítulo tal como lo guarda 009 (`definitions.md` §3 Capitulo): número, título y texto
         *     plano con párrafos separados por una línea en blanco.
         */
        CapituloVista: {
            /** Number */
            number: number;
            /** Title */
            title: string;
            /** Text */
            text: string;
        };
        /** CharacterEntry */
        CharacterEntry: {
            /** Id */
            id: number;
            /** Type */
            type: string;
            /** Species */
            species: string;
            /** Canonical Name */
            canonical_name: string;
            /** Birth Date */
            birth_date: string | null;
            /** Origin */
            origin: string;
        };
        /**
         * Chronology
         * @description La cronología registrada de una versión (`architecture.md` §4.5): los eventos de origen
         *     brief y registrados, por momento y a igual momento por id; las fechas de nacimiento que hay;
         *     la fecha del novum, si hay mundo. La leen 007 y la API.
         */
        Chronology: {
            /** Events */
            events: components["schemas"]["EventEntry"][];
            /** Births */
            births: components["schemas"]["BirthEntry"][];
            /** Novum Date */
            novum_date: string | null;
        };
        /**
         * EntidadFicha
         * @description Una fila de la `FichaDePersonajes`: nombre canónico, tipo y los capítulos donde aparece
         *     (por `UsoDeHecho` o evento registrado, `definitions.md` §3). Vacía si no aparece en ninguno
         *     (013-C03).
         */
        EntidadFicha: {
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Chapters */
            chapters: number[];
        };
        /** EventEntry */
        EventEntry: {
            /** Id */
            id: number;
            /** Statement */
            statement: string;
            /**
             * Moment
             * Format: date-time
             */
            moment: string;
            /** Place Id */
            place_id: number;
            /** Presences */
            presences: components["schemas"]["PresenceEntry"][];
            /**
             * Type
             * @enum {string}
             */
            type: "ordinary" | "exclusion";
            /** Excluded Character Id */
            excluded_character_id: number | null;
            /** Analepsis */
            analepsis: boolean;
            /**
             * Origin
             * @enum {string}
             */
            origin: "brief" | "planned" | "recorded";
            /** Chapter */
            chapter: number | null;
            /** Beat */
            beat: number | null;
        };
        /**
         * FactEntry
         * @description Un hecho con los capítulos que lo usan, en orden ascendente; `nominal` si su valor es un
         *     nombre propio (`definitions.md` §2 Hecho nominal).
         */
        FactEntry: {
            /** Id */
            id: number;
            /** Subject Type */
            subject_type: string;
            /** Character Id */
            character_id: number | null;
            /** Place Id */
            place_id: number | null;
            /** Attribute */
            attribute: string;
            /** Value */
            value: string;
            /** Origin */
            origin: string;
            /** Mandatory */
            mandatory: boolean;
            /** Personal Element Id */
            personal_element_id: number | null;
            /** Nominal */
            nominal: boolean;
            /** Chapters */
            chapters: number[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Access Token */
            access_token: string;
        };
        /** PlaceEntry */
        PlaceEntry: {
            /** Id */
            id: number;
            /** Canonical Name */
            canonical_name: string;
            /** Description */
            description: string;
            /** Origin */
            origin: string;
        };
        /** PresenceEntry */
        PresenceEntry: {
            /** Character Id */
            character_id: number;
            /** Declared Age */
            declared_age: number | null;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** RegisterResponse */
        RegisterResponse: {
            /** Id */
            id: number;
            /** Email */
            email: string;
        };
        /**
         * StoryBible
         * @description El canon de una versión (`definitions.md` §2 StoryBible): lo leen 010 a 016 por dentro,
         *     de cualquier versión, y la API, de las publicadas.
         */
        StoryBible: {
            /** Version Id */
            version_id: number;
            /** Present Year */
            present_year: number;
            world: components["schemas"]["WorldEntry"] | null;
            /** Characters */
            characters: components["schemas"]["CharacterEntry"][];
            /** Places */
            places: components["schemas"]["PlaceEntry"][];
            /** Facts */
            facts: components["schemas"]["FactEntry"][];
            chronology: components["schemas"]["Chronology"];
        };
        /** StoryBibleResponse */
        StoryBibleResponse: {
            /** Version */
            version: number;
            story_bible: components["schemas"]["StoryBible"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VersionDetailResponse */
        VersionDetailResponse: {
            /** Version */
            version: number;
            view: components["schemas"]["VersionViewData"];
        };
        /** VersionSummary */
        VersionSummary: {
            /** Number */
            number: number;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Changed Chapters */
            changed_chapters: number[];
        };
        /**
         * VersionViewData
         * @description Entrada del render: lo que 009 expone de una `Version` para pintar su `VistaDeVersion`.
         *
         *     `version_number` es `None` en una candidata (009-I1: solo las publicadas tienen número); la
         *     marca «cambiado en vN» cae entonces a «cambiado», sin número.
         */
        VersionViewData: {
            /** Title */
            title: string;
            /** Recipient */
            recipient: string;
            /** Dedication */
            dedication: string;
            /** Version Number */
            version_number: number | null;
            /** Chapters */
            chapters: components["schemas"]["CapituloVista"][];
            /** Changed Chapters */
            changed_chapters: number[];
            /** Ficha */
            ficha: components["schemas"]["EntidadFicha"][];
        };
        /** VersionsListResponse */
        VersionsListResponse: {
            /** Versions */
            versions: components["schemas"]["VersionSummary"][];
        };
        /** WorldEntry */
        WorldEntry: {
            /** Id */
            id: number;
            /** Novum Description */
            novum_description: string;
            /** Novum Scope */
            novum_scope: string;
            /**
             * Novum Date
             * Format: date
             */
            novum_date: string;
            /** Consequences */
            consequences: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_story_bible_api_novels__novel_id__story_bible_get: {
        parameters: {
            query?: {
                version?: number | null;
            };
            header?: never;
            path: {
                novel_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryBibleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_versions_api_novels__novel_id__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                novel_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionsListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_version_api_novels__novel_id__versions__number__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                novel_id: number;
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_version_pdf_api_novels__novel_id__versions__number__pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                novel_id: number;
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    view_version_view_versions__version_id__get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path: {
                version_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
