"""Write Input/Data.lean from the chronology JSON of lean/README.md.

    python3 scripts/generate.py chronology.json > Input/Data.lean

The JSON comes from outside the repository —the backend, through workflow_dispatch—, so this
script is the boundary: it checks the shape of every field and emits only numbers and fixed Lean
tokens, never text taken from the input. It checks no invariant: that is Lean's job.
"""
from __future__ import annotations

import base64
import binascii
import json
import re
import sys
import zlib
from dataclasses import dataclass
from pathlib import Path

FORMAT_VERSION = 1
MAX_EVENTS = 1000
MAX_CHARACTERS = 500
MAX_ID = 2**63 - 1
MAX_AGE = 200
MAX_JSON_BYTES = 2_000_000

DATE = re.compile(r"(\d{4,6})-(\d{2})-(\d{2})")
MOMENT = re.compile(r"(\d{4,6})-(\d{2})-(\d{2})T(\d{2}):(\d{2})")
DIGITS = re.compile(r"\d{1,19}")

TOP_KEYS = {"version", "characters", "events"}
CHARACTER_KEYS = {"id", "birth_date"}
EVENT_KEYS = {
    "id", "moment", "place_id", "characters", "type", "excluded_character_id",
    "declared_ages", "chapter_number", "beat_number", "flashback",
}


class ChronologyError(ValueError):
    """The input is not a chronology of lean/README.md."""


@dataclass(frozen=True)
class Date:
    year: int
    month: int
    day: int


@dataclass(frozen=True)
class Moment:
    year: int
    month: int
    day: int
    hour: int
    minute: int


@dataclass(frozen=True)
class Character:
    id: int
    birth: Date | None


@dataclass(frozen=True)
class Event:
    id: int
    moment: Moment
    place: int | None
    present: tuple[int, ...]
    narration: tuple[int, int] | None
    flashback: bool
    excluded: int | None
    ages: tuple[tuple[int, int], ...]


@dataclass(frozen=True)
class Chronology:
    characters: tuple[Character, ...]
    events: tuple[Event, ...]


def decode(encoded: str) -> object:
    """The JSON of a workflow input: gzip-compressed, then base64-encoded (ADR 0004)."""
    try:
        compressed = base64.b64decode(encoded, validate=True)
        inflater = zlib.decompressobj(wbits=16 + zlib.MAX_WBITS)
        raw = inflater.decompress(compressed, MAX_JSON_BYTES + 1)
    except (binascii.Error, zlib.error) as error:
        raise ChronologyError(f"the input is not base64-encoded gzip: {error}") from None
    if len(raw) > MAX_JSON_BYTES or inflater.unconsumed_tail:
        raise ChronologyError(f"the JSON exceeds {MAX_JSON_BYTES} bytes")
    if not inflater.eof:
        raise ChronologyError("the gzip stream is truncated")
    try:
        return json.loads(raw.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as error:
        raise ChronologyError(f"the input is not JSON: {error}") from None


def parse(data: object) -> Chronology:
    """Check the shape of the chronology JSON and return it typed."""
    document = _object(data, "the document", TOP_KEYS)
    if document["version"] != FORMAT_VERSION or isinstance(document["version"], bool):
        raise ChronologyError(f"version: only version {FORMAT_VERSION} exists")
    characters = tuple(
        _character(item, f"characters[{i}]")
        for i, item in enumerate(_list(document["characters"], "characters", MAX_CHARACTERS))
    )
    known = _unique([c.id for c in characters], "characters")
    events = tuple(
        _event(item, f"events[{i}]", known)
        for i, item in enumerate(_list(document["events"], "events", MAX_EVENTS))
    )
    _unique([e.id for e in events], "events")
    return Chronology(characters, events)


def render(chronology: Chronology) -> str:
    """The Lean module Input.Data, which defines `Input.chronology`."""
    lines = [
        "import Chronology.Model",
        "",
        "/-! Generated by scripts/generate.py from the chronology JSON of lean/README.md. -/",
        "",
        "namespace Input",
        "",
        "def chronology : Chronology where",
    ]
    lines += _lean_list("characters", [_lean_character(c) for c in chronology.characters])
    lines += _lean_list("events", [_lean_event(e) for e in chronology.events])
    lines += ["", "end Input", ""]
    return "\n".join(lines)


def _object(value: object, where: str, keys: set[str]) -> dict:
    if not isinstance(value, dict):
        raise ChronologyError(f"{where}: expected an object")
    unknown = sorted(set(value) - keys)
    if unknown:
        raise ChronologyError(f"{where}: unknown fields {unknown}")
    missing = sorted(keys - set(value))
    if missing:
        raise ChronologyError(f"{where}: missing fields {missing}")
    return value


def _list(value: object, where: str, maximum: int) -> list:
    if not isinstance(value, list):
        raise ChronologyError(f"{where}: expected a list")
    if len(value) > maximum:
        raise ChronologyError(f"{where}: more than {maximum} items")
    return value


def _nat(value: object, where: str, maximum: int = MAX_ID) -> int:
    if isinstance(value, bool) or not isinstance(value, int) or not 0 <= value <= maximum:
        raise ChronologyError(f"{where}: expected a whole number from 0 to {maximum}")
    return value


def _optional_nat(value: object, where: str) -> int | None:
    return None if value is None else _nat(value, where)


def _unique(ids: list[int], where: str) -> set[int]:
    if len(set(ids)) != len(ids):
        raise ChronologyError(f"{where}: repeated ids")
    return set(ids)


def _is_leap(year: int) -> bool:
    return year % 4 == 0 and (year % 100 != 0 or year % 400 == 0)


def _days_in_month(year: int, month: int) -> int:
    if month == 2:
        return 29 if _is_leap(year) else 28
    return 30 if month in (4, 6, 9, 11) else 31


def _date(value: object, where: str) -> Date:
    match = DATE.fullmatch(value) if isinstance(value, str) else None
    if match is None:
        raise ChronologyError(f"{where}: expected a date YYYY-MM-DD")
    year, month, day = (int(group) for group in match.groups())
    if not 1 <= month <= 12 or not 1 <= day <= _days_in_month(year, month):
        raise ChronologyError(f"{where}: no such date")
    return Date(year, month, day)


def _moment(value: object, where: str) -> Moment:
    match = MOMENT.fullmatch(value) if isinstance(value, str) else None
    if match is None:
        raise ChronologyError(f"{where}: expected a moment YYYY-MM-DDTHH:MM")
    year, month, day, hour, minute = (int(group) for group in match.groups())
    if not 1 <= month <= 12 or not 1 <= day <= _days_in_month(year, month):
        raise ChronologyError(f"{where}: no such date")
    if hour > 23 or minute > 59:
        raise ChronologyError(f"{where}: no such time")
    return Moment(year, month, day, hour, minute)


def _character(value: object, where: str) -> Character:
    item = _object(value, where, CHARACTER_KEYS)
    birth = item["birth_date"]
    return Character(
        _nat(item["id"], f"{where}.id"),
        None if birth is None else _date(birth, f"{where}.birth_date"),
    )


def _event(value: object, where: str, known: set[int]) -> Event:
    item = _object(value, where, EVENT_KEYS)
    present = [_nat(c, f"{where}.characters") for c in _list(item["characters"], f"{where}.characters", MAX_CHARACTERS)]
    if len(set(present)) != len(present) or not set(present) <= known:
        raise ChronologyError(f"{where}.characters: repeated or unknown characters")
    if item["type"] not in ("ordinary", "exclusion"):
        raise ChronologyError(f"{where}.type: expected 'ordinary' or 'exclusion'")
    excluded = _optional_nat(item["excluded_character_id"], f"{where}.excluded_character_id")
    if (item["type"] == "exclusion") != (excluded is not None) or (excluded is not None and excluded not in known):
        raise ChronologyError(
            f"{where}.excluded_character_id: a known character exactly when the type is 'exclusion'"
        )
    chapter = _optional_nat(item["chapter_number"], f"{where}.chapter_number")
    beat = _optional_nat(item["beat_number"], f"{where}.beat_number")
    if (chapter is None) != (beat is None):
        raise ChronologyError(f"{where}.beat_number: both chapter_number and beat_number, or neither")
    if not isinstance(item["flashback"], bool):
        raise ChronologyError(f"{where}.flashback: expected true or false")
    return Event(
        id=_nat(item["id"], f"{where}.id"),
        moment=_moment(item["moment"], f"{where}.moment"),
        place=_optional_nat(item["place_id"], f"{where}.place_id"),
        present=tuple(present),
        narration=None if chapter is None or beat is None else (chapter, beat),
        flashback=item["flashback"],
        excluded=excluded,
        ages=_ages(item["declared_ages"], f"{where}.declared_ages", known),
    )


def _ages(value: object, where: str, known: set[int]) -> tuple[tuple[int, int], ...]:
    if not isinstance(value, dict):
        raise ChronologyError(f"{where}: expected an object from character id to age")
    ages = []
    for key, age in value.items():
        if not isinstance(key, str) or DIGITS.fullmatch(key) is None or int(key) not in known:
            raise ChronologyError(f"{where}: keys are the ids of known characters")
        ages.append((int(key), _nat(age, where, MAX_AGE)))
    return tuple(sorted(ages))


def _lean_list(field: str, items: list[str]) -> list[str]:
    if not items:
        return [f"  {field} := []"]
    return [f"  {field} := ["] + [f"    {item}," for item in items[:-1]] + [f"    {items[-1]}", "  ]"]


def _lean_option(value: int | None) -> str:
    return "none" if value is None else f"some {value}"


def _lean_character(character: Character) -> str:
    birth = "none" if character.birth is None else (
        f"some (Chronology.Date.mk {character.birth.year} {character.birth.month} {character.birth.day})"
    )
    return f"{{ id := {character.id}, birth := {birth} }}"


def _lean_event(event: Event) -> str:
    m = event.moment
    narration = "none" if event.narration is None else (
        f"some (Chronology.Position.mk {event.narration[0]} {event.narration[1]})"
    )
    ages = ", ".join(f"Chronology.DeclaredAge.mk {c} {a}" for c, a in event.ages)
    return (
        f"{{ id := {event.id}, moment := Chronology.Moment.mk {m.year} {m.month} {m.day} {m.hour} {m.minute},"
        f" place := {_lean_option(event.place)}, present := [{', '.join(map(str, event.present))}],"
        f" narration := {narration}, flashback := {'true' if event.flashback else 'false'},"
        f" excluded := {_lean_option(event.excluded)}, ages := [{ages}] }}"
    )


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print(__doc__.strip().splitlines()[2].strip(), file=sys.stderr)
        return 2
    try:
        data = json.loads(Path(argv[1]).read_text(encoding="utf-8"))
        sys.stdout.write(render(parse(data)))
    except (OSError, json.JSONDecodeError, ChronologyError) as error:
        print(f"generate.py: {error}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
